spring.application.name=worktime-backend


spring.datasource.url=jdbc:postgresql://localhost:5432/worktime
spring.datasource.username=postgres
spring.datasource.password=Feab0906

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true